football_analysis:
  outputs:

    dev:
      dbname: "{{ env_var('POSTGRES_DB') }}"
      host: "{{ env_var('POSTGRES_HOST') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      schema: analysis
      threads: 1
      type: postgres
      user: "{{ env_var('POSTGRES_USER') }}"
  target: dev
