-- LOAD DATA LOCAL INFILE
-- '/tmp/football/leagues.csv' INTO TABLE
-- leagues FIELDS TERMINATED BY ',' LINES TERMINATED BY
-- '\n' IGNORE 1 ROWS;


-- LOAD DATA LOCAL INFILE
-- '/tmp/football/teams.csv' INTO TABLE
-- teams FIELDS TERMINATED BY ',' LINES TERMINATED BY
-- '\n' IGNORE 1 ROWS;


-- LOAD DATA LOCAL INFILE '/tmp/football/players.csv' 
-- INTO TABLE players 
-- CHARACTER SET utf8mb4
-- FIELDS TERMINATED BY ',' 
-- LINES TERMINATED BY '\n' 
-- IGNORE 1 ROWS;


-- LOAD DATA LOCAL INFILE
-- '/tmp/football/games.csv' INTO TABLE
-- games FIELDS TERMINATED BY ',' LINES TERMINATED BY
-- '\n' IGNORE 1 ROWS;

-- LOAD DATA LOCAL INFILE
-- '/tmp/football/teamstats.csv' INTO TABLE
-- teamstats FIELDS TERMINATED BY ',' LINES TERMINATED BY
-- '\n' IGNORE 1 ROWS;

-- LOAD DATA LOCAL INFILE
-- '/tmp/football/appearances.csv' INTO TABLE
-- appearances FIELDS TERMINATED BY ',' LINES TERMINATED BY
-- '\n' IGNORE 1 ROWS;

-- LOAD DATA LOCAL INFILE
-- '/tmp/football/shots.csv' INTO TABLE
-- shots FIELDS TERMINATED BY ',' LINES TERMINATED BY
-- '\n' IGNORE 1 ROWS;



LOAD DATA LOCAL INFILE'/tmp/football/players.csv' INTO TABLE players FIELDS TERMINATED BY ',' ENCLOSED BY '"'  LINES TERMINATED BY'\n' IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE'/tmp/football/transfers.csv' INTO TABLE transfers FIELDS TERMINATED BY ',' ENCLOSED BY '"'  LINES TERMINATED BY'\n' IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE'/tmp/football/player_valuations.csv' INTO TABLE player_valuations FIELDS TERMINATED BY ',' ENCLOSED BY '"'  LINES TERMINATED BY'\n' IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE'/tmp/football/games.csv' INTO TABLE games FIELDS TERMINATED BY ',' ENCLOSED BY '"'  LINES TERMINATED BY'\n' IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE'/tmp/football/club_games.csv' INTO TABLE club_games FIELDS TERMINATED BY ',' ENCLOSED BY '"'  LINES TERMINATED BY'\n' IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE'/tmp/football/clubs.csv' INTO TABLE clubs FIELDS TERMINATED BY ',' ENCLOSED BY '"'  LINES TERMINATED BY'\n' IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE'/tmp/football/competitions.csv' INTO TABLE competitions FIELDS TERMINATED BY ',' ENCLOSED BY '"'  LINES TERMINATED BY'\n' IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE'/tmp/football/game_events.csv' INTO TABLE game_events FIELDS TERMINATED BY ',' ENCLOSED BY '"'  LINES TERMINATED BY'\n' IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE'/tmp/football/game_lineups.csv' INTO TABLE game_lineups FIELDS TERMINATED BY ',' ENCLOSED BY '"'  LINES TERMINATED BY'\n' IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE'/tmp/football/appearances.csv' INTO TABLE appearances FIELDS TERMINATED BY ',' ENCLOSED BY '"'  LINES TERMINATED BY'\n' IGNORE 1 ROWS;